### ISSUE TITLE
Only use HTTPS in Jira URLS

### ISSUE THREAD

**Issue by paul-lemon** [ljay79/jira-tools#142]
Because basic authentication or JIRA API should be kept and transmitted securely only the Add on should only accept HTTPS urls. Allowing the user to enter HTTP introduces a security risk with their credentials being transmitted insecurely the Add-On should prevent users from accidentally doing this.

**Comment by ljay79** [comment]
Fully agree, however i had already users with custom self hosted Jira instances without SSL.
But i think, this is something we should soon enforce - going with the wave of enforced SSL everyhwere.

Similar to some of the other issues for code tweaking/renaming/organizing, i suggest to get a stable master branch with released IssueUpdate feature first. Then wait a little for bugs coming in, then when really stable apply all the styling tweaks at once and release again...
Otherwise we will soon have multiple branches and busy merging back and forth...

**Comment by paul-lemon** [comment]
Agree on not opening more branches - maintaining the current one is a PIA - need to get to smaller less long lived branches.

**Comment by paul-lemon** [comment]
Perhaps a good first step if you still have users who *must* have HTTP is to show a big RED error box when they use HTTP and advising them to use HTTPS
