### ISSUE TITLE
There was a problem  fetching your settings from the Google Service

### ISSUE THREAD

**Issue by rodrigomojeda** [ljay79/jira-tools#196]
** Provide a general summary of the issue in the Title above **

All of my queries fail with a generic error that's not possible to debug.
Error: There was a problem fetching your settings from the Google Service. Please try again later. (line 21)

** Provide a more detailed information of the issue **
I'm not able to access Add-on configuration I get this error "Service called too frequently in one day: properties get".
I assume that I'm reaching Google API limits. In such case IDK why it is happening so often.
 
** Provide Debugging information **
Sadly I can't activate the debug mode due to the "Service called too frequently in one day: properties get" issue.

**Comment by ljay79** [comment]
Hi there.
Sorry that you have such issue.
This error would usually occure, when the script is not able to access the storage object from google which in most cases would only occure when the add-on is not authorized to access it.

Did you try to fully uninstall the add-on?
Then install it but do this in a completly new and empty google sheet of your own. Then test again please and report here, if it helped.

**Comment by ljay79** [comment]
Hi @rodrigomojeda 
do you have any update to that issue?

**Comment by rodrigomojeda** [comment]
Hi Sorry for the late response.
Well, the thing is that I've already tried to uninstall/install with apparently no luck.  
Let me give some more background.
I'm using the add-on in several spreadsheets simultaneously to grab data from Jira and to create various teams performance metrics.
The problem is that when I start getting this error it got spread all over the other automation spreadsheets, I assume that add-on is using my credentials so when one instance fails the others fail as well.
Quick questions: You've said that this error is being caused by " the script is not able to access the storage object from google "

How can I avoid this or even track/debug this error?

Can you elaborate on how the script is accessing the storage object?

Looking forward.
Thank in advance

**Comment by ljay79** [comment]
Hi.

Your issue and your feedback indicate it might be simply related to an overly heavy use, reaching the google quota limits.
If you uninstall the add-on, i would try to leave it uninstalled for 24 hours.

And yes, for sure, if 1 sheets add-on fails, all other will do same.
An Google Add-On is not limited to a specific sheet. It will life in your google user account within the Sheet service in general, not just within a single spreadsheet.

Regarding storage object:
The add-on does safe a few details like your Jira credentials and settings within a storage service provided by google specifically for Google Sheet Add-Ons.
Using the add-on will require access to the storage of such details and settings in order to work properly.

When you install an add-on, such as mine, it will also require some permissions including such storage access.

When you uninstall the add-on, it would remove everything from that storage, any permissions granted and any triggers this add-on did setup. For sure, all your sheets which using custom functions wont work at this time.

**Comment by rodrigomojeda** [comment]
Hi Jens,
Thanks for the prompt response!
Yep, everything indicates that I'm reaching Google's quota.
I'll try leaving it uninstalled over the weekend, keep you posted.
What's your guess about leaving it uninstalled for 24hs?
Looking forward.
Regards

**Comment by ljay79** [comment]
As the google quota limits are per 24hours, it should be fine over the weekend.
When you then reinstall the add-on, please do this in a completly new and empty Spreadsheet. Just to try making safe, no old/existing sheet will trigger any Jira api requests (add-on activities).

Then for testing, try to replicate your use case step by step until you hit the issue again.
PS: Suggestion: when re-installing after the weekend, do enable the Debugging option in the "About" dialog right away and make note of the shows "Temp user key". As you mentioned, once you hit the issue again, you wont be able to do this afterwards.

With the debugging active and the temp user key, i can check all my StackDriver logs for your use case and investigate deeper - on your request.

Keep me posted pls in any case.

**Comment by rodrigomojeda** [comment]
Thanx Jen,
I'll keep you posted.
Regards

**Comment by ljay79** [comment]
Hey @rodrigomojeda do you have any update on your above issue?

**Comment by rodrigomojeda** [comment]
Yes, after following your recommendations issue did not occur again.
Thank you.
Regards
