### ISSUE TITLE
List Issues from Filter Not Returning All Fields Requested (11 of 17)

### ISSUE THREAD

**Issue by jeffrmanley** [ljay79/jira-tools#205]
The List Issues from Filter is no longer returning all fields requested. It shows 12 headers when it should be 17. It is only displaying data for 11 of the 12 fields. 

We recently renamed a fields from "Actual ETA" to "ETC" in Jira. I deleted the custom fields from Configure Custom Fields and then re-added them. I also created a new new clean worksheet and it gives the same result. 

I turned on our temp user key:  AANBUuXNismlhcD+t9PM+7mpDK0BGVZPDJjwIlJzWkmkwOLjMNu5D6JQAiQ7/pAOe8gfrgSkc8YU

I'll attach screen shots

**Comment by jeffrmanley** [comment]
![ShowsOnly12FieldHeaders](https://user-images.githubusercontent.com/1508856/56928511-e1a20180-6a8b-11e9-9184-7ba8bf532e12.PNG)
![SelectedFilterandFields](https://user-images.githubusercontent.com/1508856/56928516-e49cf200-6a8b-11e9-8ff6-2c09198cce0c.PNG)

**Comment by jeffrmanley** [comment]
![ShowsOnly12FieldHeaders](https://user-images.githubusercontent.com/1508856/56928533-ef578700-6a8b-11e9-809e-6214fa88fdac.PNG)

**Comment by jeffrmanley** [comment]
I further tested further using =JST_search("project=IMPSMSM","key,created, workstream,updated,WIPCompletedTime",100,0) 

See screenshot for what was returned

![CustomField](https://user-images.githubusercontent.com/1508856/56928639-4c533d00-6a8c-11e9-9527-6367f42feaa0.PNG)

**Comment by jeffrmanley** [comment]
@ljay79  - we are still having issues with this....any suggestions?

**Comment by ljay79** [comment]
Hi, sry for late reply.
Im a little busy atm. Will investigate it over the next days and check if i am able to replicate it an/or fix it.

**Comment by ljay79** [comment]
About 2) 
> ...=JST_search("project=IMPSMSM","key,created, workstream,updated,WIPCompletedTime",100,0)
Im sure this is because the custom functions like _JST_search()_ do not understand the names of custom fields. Yould need to use the actual jira key id. You can find it by looking up your field with the Jira Field Map over the add-on's menu.

It would then look like:
`=JST_search("project=IMPSMSM","key,created, workstream,updated,customfield_12345",100,0)` 

About 1)
Im trying to replicate this. Any further details would be helpful.
So far, i wasnt able to replicate. 
I created a new filter which do returns me 2 different jira issues from 2 different projects. 1 issue has a custom field, which the other issues scheme doest. In the google sheet it returns as expected, the value for one issue and an empty cell for the other.

**Comment by ljay79** [comment]
Good news...
I was able to reproduce it now. Apparently you are using different "Field Configurations" for your projects.
Some project have certain fields hidden some now. Your filter is quering issues across multiple projects where not all of them have your desired custom fields available.
My add-on apparently is not capable of working with such behavior in the data.

As i have now a way of reproducing and testing it, i will now start on working a solution for such cases.
Please give me a little time :)    (PS: This is a private low prio project to me still)

**Comment by ljay79** [comment]
Hi @jeffrmanley in the latest release v1.3.4 i have applied a fix which should solve your issue now.

**Comment by jeffrmanley** [comment]
Hi @ljay79 ...thanks for the quick fix. I confirm it is working!! You are the BEST!!

**Comment by ljay79** [comment]
Great. After all, bug reports are very important. It allows me to make this addon better for everyone.

I would appreciate a positive review in the Google marketplace ;)
