### ISSUE TITLE
Refresh Issue Table does not pick-up modified JQL

### ISSUE THREAD

**Issue by skorecki** [ljay79/jira-tools#208]
I have a JQL filter that I have modified several times after Listing Issues from Filter in Google Sheets w/ProjectAid for Jira.  None of these modifications (ex. filtering out Cancelled issues) take effect in the Google Sheet when Refreshing the Issue Table.  Only after deleting all cells in the sheet and starting over by choosing a new "List Issues from Filter", was the updated JQL reflected in the sheet.  Please have ProjectAid for Jira get the updated JQL everytime the issue table is refreshed.

**Comment by ljay79** [comment]
Hi @skorecki thanks for reporting this.
At the moment, this is the expected behavior, as it does refresh the table already present in the sheet, its not expected to dynamically use an updated filter and recreate a table with modified column count.

Not sure, if this would be the way most user would expect... I keep this open here a while to see other users feedback and check back on it later.

**Comment by ljay79** [comment]
Hi @skorecki in the latest release v1.3.4 i have applied a fix which should solve your issue now.

**Comment by skorecki** [comment]
Thanks for fixing this!  I think this behavior is now very helpful and intuitive.
