### ISSUE TITLE
Create and refresh issue table from filter function doesn't work from yesterday afternoon

### ISSUE THREAD

**Issue by noraszel** [ljay79/jira-tools#247]
When I click to "Refresh issue table" on a earlier created issue table or "Create IssueTable from filter" button in the menu, I get this error massage:
<img width="880" alt="Screenshot 2020-03-11 at 9 38 21" src="https://user-images.githubusercontent.com/60604822/76403924-f0349700-6385-11ea-8225-8d56d75ab765.png">
I already reinstalled the add-on, but that did not help.

**Comment by ljay79** [comment]
Hi @noraszel thanks for reporting your issue.
I wasnt able to reproduce it yet.

Could you please provide further debugging information:
For further investigation, please activate Debugging in "About" dialog, provide us with your "Temp. User Key" and then perform at least one another try. This way it will log the error and debug information to project owners StackDriver logging account where we can analyze it better.
>Note: User credentials are not transmitted in any log data.

**Comment by noraszel** [comment]
Hi @ljay79 thanks for your quick answer.
This is the "Temp.User.Key" about my last try: APZqPaxDGL3LCiKdD+hVUXl+aebZ25TW5mOq7AjFkAFYjYi9GVQUm9Sfi3fdc3U0k4U8Hy1BBerk

**Comment by ljay79** [comment]
Thanks.
Thats interesting. So checking my code, i can tell (almost sure) its triggered from an internal error handler. It does check, if you try to insert/update a IssueTable which overlaps with a different table.
Usually it should raise a error with message like:
`You are trying to insert a new IssueTable within an existing IssueTable. Please delete existing IssueTable or choose an empty cell/range in your sheet.` 

However, it appears, the UI fails to render that message and instead you get such strange message.

Having said that, i believe you can resolve this issue simple by creating a new Sheet (or even entire new Spreadsheet) and insert the table again on a fresh an clean sheet.

Let me know, if this helped.

**Comment by noraszel** [comment]
Creating a new Sheet did not resolve the issue, but with a brand new Spreadsheet it is working.
But the main problem, that I have a really big Spreadsheet with many Sheets (with reports) which based on this Issue Tables.
I refresh the issue tables every day and my Status tables are allways up to date. So I will create a brand new Spreadsheet now but that is a very big task so I do not want to do this often.
Could you help me how can I prevent this problem? I only would like to  refresh this tables every day. (I only tried to create a new one, because the refreshing did not work.)

**Comment by ljay79** [comment]
Its very hard to debug this from here.
If im not mistaken, i believe one of the IssueTables in the affected Sheet got modified manually (outside of the add-on) and is now not available for the add-on features (Refresh) anymore.

From what i programmed into the code; such IssueTables and its meta data is stored *per sheet* so an issue on Sheet A wouldnt affect Sheet B.

That would mean, the issue you expiriencing (as i can atm only guess) is related to a specific sheet and creating a new Sheet (not even an new Spreadsheet) should already solve the issue.
With solving; i mean deleting the affected/corrupted sheet and creating it new.

However, this observation doesnt really match with your explanation, that it apparently is not limited to a single sheet if i understood correctly.
You saying, the "Refresh" action doesnt work on *any* of the tables in *any* sheet of your main Spreadsheet?

> Note: When ever a new IssueTable is inserted into a sheet. The code triggers a cleanup. It should reindex all available IssueTables on the current sheet and remove orphaned or currupted meta data / IssueTables.
Means. When there is a manually or otherwise corrupted IssueTable on the current sheet, it would be unlinked from the add-on. Data in cells would persist, but the IssueTable would be removed from the sidebar and therefore doesnt have an "Refresh" option anymore.

**Comment by noraszel** [comment]
Yes, you understood correctly.
My Spreadsheet contain three Sheets of "IssueTable from filter" and I could not refresh none.

**Comment by ljay79** [comment]
strange...  let me know in case you can provides some more details which might make me able to reproduce the issue.

I can currently no think of the reason for it nor of the cause :( sry

**Comment by noraszel** [comment]
OK, I let switch on the Debbuging function, so if this problem is come up again, you will have more information about this.
By the way, I love this add-on, so thank you very much your work. :)

**Comment by ljay79** [comment]
Hi @noraszel are you still experiencing this issue?
If so, can you enable the debugging, perform the issue with problems and then pls report back to me with your temp user key and the timeframe of this execution. I can then more specific analyze just your debug logs.

**Comment by ljay79** [comment]
Hi @noraszel i wasnt able to find any new clue on that issue.
Was you able to find any new clue?

**Comment by noraszel** [comment]
Hi @ljay79, thank you everything is fine since my last update. I can close the issue. Thank you your work with this tool, I really love it. 🥇
