### ISSUE TITLE
Filter Results Cap at 200

### ISSUE THREAD

**Issue by yashar1** [ljay79/jira-tools#25]
I've connected to a filter that should return (and currently returns in JIRA) 6,300 results.

The sheet is capping out at the first 200 results. 

I'm using On Demand which should produce at least 1,000 results.

Any ideas of what could be causing this? Thank you!

**Comment by ljay79** [comment]
Hi @yashar1 i will check out this soon.
My JIRA instance i can test with wont support 6k results but i should have something with much more than 200 to reproduce it...

**Comment by ljay79** [comment]
Ok @yashar1 no problem.
I found the reason, i have purposely a limit of 200 results maximum hard coded in the add-on, because this request is quite resource consuming and taking long.

But i will increase the limit and maybe add some more extended logic.
If you can wait a few more days, then i will release a new version anyway with a new feature for getting worklogs as a Timesheet.

Sry for the hard limit...

**Comment by yashar1** [comment]
@ljay79 

Thanks for the update, I'll stay put for the new changes!

**Comment by ljay79** [comment]
Hi @yashar1 ,
a new version is out since yesterday. It should already automatically have updated your installed one.
The maximum result is now to default 1000.
Please check if that helped and let me know.

In one of the future versions i will refactor the function to allow pagination over actual all total results. Maybe a few weeks though 👍

**Comment by yashar1** [comment]
@ljay79 ,
Works great, I'll check back for the all total results function!

Thank you once again
