### ISSUE TITLE
Could not connect to Jira server

### ISSUE THREAD

**Issue by alexgarner** [ljay79/jira-tools#66]
Hi I am getting a 500 error when trying to set up the settings.

Hopefully, this tool will connect and I can get it to work as it looks great!

![image](https://user-images.githubusercontent.com/22801521/37482637-a3980170-287c-11e8-970b-04ff8dab2fde.png)

**Comment by ljay79** [comment]
Hi.

For logging in it usually requires a username rather then a email address.
Please try with your Jira username.

If it still wont work, please activate Debugging in "About" dialog, provide me your "Temp. User Key" and then perform at least one another try. This way it will log the error and information to my StackDriver logging account where i can analyze it better.
User credentials are not transmitted in any log data.

**Comment by alexgarner** [comment]
Resolved - thank you!

**Comment by knorrre** [comment]
I am getting a 500 error, too.
Some accounts are synced with GSuite but not the one I am using for login.
Login in website works fine (with username, password) and all projects are shown ansd the user is jira-admin and site-admin So no problem with rights.
Any Ideas?

**Comment by ljay79** [comment]
Hi.
I cant find your comment in GitHub - did you deleted it already because you
was able to solve your problem?
Otherwise, please comment on the ticket again so i can follow up there.

Please review the Readme first, in section "Known Issue".
https://github.com/ljay79/jira-tools#known-issues

This might help with your authentication problem.


2018-03-27 10:56 GMT+02:00 knorrre <notifications@github.com>:
