### ISSUE TITLE
Inconsistent data 

### ISSUE THREAD

**Issue by alexgarner** [ljay79/jira-tools#67]
Hi - one more issue that has popped up. 

I am getting considerable discrepancies with the reports - especially time reports. If I run the same query within moments I get different results. 

See image (can you please shed any light?) - Notice the total amount of days is different. Each time I run the report I get different a different count and collection of tickets. 

![image](https://user-images.githubusercontent.com/22801521/37521281-15253d62-2918-11e8-98bd-9ce0b19f50d3.png)

**Comment by ljay79** [comment]
Hmm thats a strange behavior and obviously not expected.
Could you please activate Debugging in "About" dialog, provide me your "Temp. User Key" and reproduce the issue.

Are you able to figure approx how many worklogs are related to the above 13 issues in total?
I could atm assume, there is an issue with the limitation of records per fetch.

**Comment by ljay79** [comment]
I do notice a few styling/formatting changes on the screenshot above.
To truely reproduce, please open a new clean sheet and create the report.

**Comment by alexgarner** [comment]
"activate Debugging in "About" dialog"

I have done this and run the same report twice.

Cheers,
A

________________________________

**Comment by ljay79** [comment]
Thx. Will have a look at it later tonight.
Can you pls provide your temp user key as described above.

**Comment by alexgarner** [comment]
AOrymO3okBl2S90wbO0px3EyvA+URwXBZoRVn2BgfDdpVwxygpqj6ct/xSdeUKowsvzFV1r6exui


________________________________

**Comment by ljay79** [comment]
At a first sight there is one error during the retrieval of all data.
For the jira issue "19392" the add-on is unable to retrieve any worklogs as it returns an error "Unauthorized".
(https://raremark.atlassian.net/rest/api/2/issue/19392/worklog)
Can you try to access that URL in same browser where you are logged in to Jira and see if it returns anything. And/Or go to Jira and get view the related Jira ticket, browse down and try to view the worklog  of it. It seems to be a permission issue

again, just on my first sighting.

**Comment by ljay79** [comment]
2 other things;

a) the logs show me, you appear to run an Add-On version 0.21.1 while the latest version available in google app store is: _v.1.21.2_

b) During your activity using the add-on it perform multiple api requests to your Jira instance. Every now and then the logs show random failed request with error *500 Unauthorized*.
This isnt normal, however even Jira Cloud Service is not 100% perfect. I will dig deeper and also check if i find any recent issue reports from Jira services themself.

**Comment by alexgarner** [comment]
Thanks, Jens.


Best,

A


________________________________

**Comment by ljay79** [comment]
I have analyzed your logs more deeply. When fetching the worklogs for the individual related jira tickets, it has random failures where your Jira instance fails with an authorization error.
There isnt much i can do from my side atm, as it is unclear why the used Jira instance would fail with such reason during one of many calls.

The only thing i will be able to do atm, i will see how i can make such issue more transparent in a way that the resulting time sheet is able to visualize such issues. This way, its still not fixed for your case but at least it would give the user an indicator that the data shown isnt complete.

Are you getting any other unexpected issues when using your Jira maybe even within Jira directly?

One last thought;
it is concerning me that it seems you are using an outdated add-on version and you had trouble at the beginning when setting the add-on up the first time.
My suggestion: close any instance of your browser.
Then open just 1 new browser window, go to google sheet, *uninstall* the Jira Sheet Tool, then reinstall it. Make sure it is running version v0.21.2 - check the add-on "About" dialog to confirm.
Then try to reproduce the issue.

It could possibly be, that due to multiple instances and failures in past, google has some data cached. Like the wrong credentials. And then during processing, it randomly uses mixed credentials (correct and wrong ones). Because technically such things all run in a multi-node environment on google, where not every node might have the same state as others. So a reinstall / reset of the add-on might actually solve your problem.

**Comment by alexgarner** [comment]
Thanks for investigating. I agree with your solution.


If you send a request to fetch the total count of issues available based on criteria provided then a simple COUNTA of the total issues received would quickly highlight any discrepancies.


I'll have a look at installing and reinstalling the app.


A


________________________________

**Comment by ljay79** [comment]
@alexgarner since today a new updated version 0.21.3 is published and available.
It wont really fix your issue, however it should now list the jira issue even when it failed to retrieve worklogs and add a note to the cell with the error message.

This way, it is at least transparent to the user, in case any issue occurred while creating a time report.

Please let me know, if you find out anything further or if the issue soled (itself). Sometimes its really just Jira Atlassian itself, that their service has interruptions or other malfunctions - speaking from experience.

**Comment by alexgarner** [comment]
Thanks, Jens.


I will have another look today.


Best,

A


________________________________

**Comment by ljay79** [comment]
Any update?

**Comment by ljay79** [comment]
closed due to inactivity
