### ISSUE TITLE
Is it possible to refresh all fields when clicking "Refresh Ticket Data"? 

### ISSUE THREAD

**Issue by vivicf0312** [ljay79/jira-tools#92]
My first thought when running that option was that all fields were going to refresh, instead I have to List issues from filter again.

**Comment by ljay79** [comment]
Thx for your feedback @vivicf0312 
I will think about how to rename that menu item.
A full sheet update on plain text cells is however not possible to implement as there is no reference to any individual jira data possible to store within the sheet, beside the plain text inserted into each cells.

**Comment by gnustavo** [comment]
I also thought that the "Refresh Ticket Data" would refresh all information for each issue. Then I realized it would only refresh the cells containing the issue keys when I read the documentation.

It's not a good name for the feature, it seems. ;)

I understand now that I have to reinsert the filter again to have everything refreshed. But it's annoying, since I have to reselect the filter and possibly all the fields I'm interested in.

Wouldn't it be possible to infer the filter name from the cell "Filter: <filtername>" that you insert? As a further check you could see if the cell below that is the "Key". Then you could grok the fields by reading the cells to the right of "Key". It's a kludge, but it could be very useful and save much time and friction.

If you think it's worthwhile to thing about it I can open another issue, since this one is already closed.

Thanks!

**Comment by gnustavo** [comment]
I took a further look at the closed issues and saw that there are a few ones related to this same issue: #90 #71 #63 #30. The #86 is also somewhat related.

**Comment by ljay79** [comment]
I understand the inconvinience and the use case for updating the entire results.
However, this isnt that trivial from tech point of view as well as it would not be able to respect possible cell editing made between two insertions. In this case it might conflict with other use cases.

I think i could offer 2 compromises:
a) I will for sure have to change the naming of the menu item "Refresh Ticket Data" to be more precise.
b) I will think of a convinient way of re-inserting entire filter results based on (last choosen filter) and the selected fields - something like a Quick-Menu with Favorites

I must however say, this project isnt on my priority list and with my upcoming vacation :) i might not be able to work on that before new year 2019 :(

BTW: Im always happy if there is anyone who likes to fork the repo and contributes on the development.

**Comment by gnustavo** [comment]
Thank you, @ljay79 . I couldn't ask for more.

I'd like to provide you with a PR but I'm not fluent in JavaScript. I'm sorry.

**Comment by gnustavo** [comment]
I was reading the code and had an idea that I want to share.

The function ``insertIssuesFromFilter(jsonFormData)`` is responsible for inserting the results of a filter. What if you [set a note](https://developers.google.com/apps-script/reference/spreadsheet/range#setnotenote) to the "summary" cell containing a mark, a warning, and the original `jsonFormData`?

The _mark_ should be a unique string to allow us to find later all notes we inserted along the way. Then, when we want to refresh all filters in a sheet we can use the [getNotes](https://developers.google.com/apps-script/reference/spreadsheet/range#getnotes) method and look for the notes containing the mark. I think of something like ``[jira-tools]`` should suffice.

The _warning_ should be just a message telling the users to avoid editing or removing the note itself, so that they will be able later on to refresh the filter. I thing of something like _Don't remove or edit this note as it contains the arguments needed to refresh the Jira filter data below_.

The _jsonFormData_ is simply the JSON argumemt that was used to generate the table. I think it can be reused as is to regenerate the table, can't it?

Then, you would simply invoke ``insertIssuesFromFilter()`` again with the same arguments and in the same cell to refresh the table.

Would it work?

**Comment by ljay79** [comment]
I was thinking and trying some things regarding this feature request.

First about your last suggestion.
a) it would make sense to store any Json data anywhere, as it would be still the *old* data of the table which isnt the goal
b) having marks/notes etc in some cells would still not allow a user to update it conviniently with a short click or shortcut key combo

- Custom functions have a big limitation, as it would not allow the add-on to interact as much with the sheet as a function called via the dialogs.
Ie: custom function can only interfer with direct arbitary cells, they can only return plain data without any formatting of the cell or similar. On top of that, a custom function must be finished within 30 seconds.
Seeing user importing issue tables with a processing of over 5 minutes (over google limit) due to 1000nds of records, would cause even more limitations.

- Macros:
Macros currently wouldnt work with this addon as necessary functions are not accessible through it
A big limitation of macros; they can not be defined by the add-on itself.
Macros can only be created/recorded by the individual sheet user and are bound the the sheet.

- Buttons/Links in a cell which could act as a shortcut button wil not work, as they can not interact with the add-on functions. They do allow server-side functions only


h4. A rough idea i will investigate on further:
- creating functionality allowing a user to save a favorite Issue Table (combo from "Insert Issue from Filter" -> choosen filter + selected fields to insert
- then i could have a new menu opening a new sidebar with only all favorite issue tables
- in this sidebar, a user could choose a favorite one and just by clicking on them, it will insert a full new Issue table with the saved preferences

- to make this even quicker, now a Macro could be recorded, opening the sidebar, clicking a specific item; that macros does now support keyboard shortcuts - however must be created by a user himself

**Comment by ljay79** [comment]
hmmmm above idea got a bummer already.
Macros do not record user interaction within a dialog or sidebar. So i would be able to open the sidebar via macro but it would never know which "favorite" option to choose and trigger...

**Comment by ljay79** [comment]
I believe this is solved while ago with the feature of "Refresh IssueTable" (https://github.com/ljay79/jira-tools#refresh-issuetable)

Closing it therefor.
