### ISSUE TITLE
Macro in Google Spreadsheets

### ISSUE THREAD

**Issue by sjonniej** [ljay79/jira-tools#97]
Im not sure if it belongs here because it is not directly an issue for the tool.

When i try to make a makro it somehow won't work because there are no filters recorded when selecting. Whenever i use the recordfunction in Google Spreadsheet, he wont 'take' the filters.

`function updatetickets() {
  var spreadsheet = SpreadsheetApp.getActive();
  spreadsheet.getRange('A1').activate();
  dialogIssueFromFilter();
  spreadsheet.getRange('A19:I19').activate();
};`

Above code is created when recording an Makro. Ofcourse, the dialogIssueFromFilter is another function within the function that isn't created (yet). I have tried some things but i just can't get it to work.
The error i get: ReferenceError: 'dialogIssueFromFilter' is niet gedefinieerd.DetailsSluiten

Is there any way to get the filter or selected preferences in the "List issues from filter" to be selected?

**Comment by ljay79** [comment]
Hi @sjonniej 
you wont be able - for my knowledge - to create a macro or otherwise use an "internal" function from my or other add-ons.
Only specific "custom" functions, which are available for cell functions as well, can be called directly.

Sry to say, but i doubt you will be able to create a macro out of the add-on dialogs choices and interactions.

Did you tried my custom function "=JST_search(...)" yet, maybe that helps already.
see: https://github.com/ljay79/jira-tools/blob/master/README.md#custom-functions

**Comment by sjonniej** [comment]
Thanks for your answer. I will look at the custom functions, maybe it will help.
